### ISSUE TITLE
https problem connect with own auth server

### ISSUE THREAD

**Issue by patsys** [ContainerSSH/ContainerSSH#107]
## Please describe what you need help with
My repository is https://github.com/patsys/containerSSH/tree/develop use version 4.0.0-RC3

I get a connection error from the ContianerSSH to my auth server with a selfsigned Certificate.

ContainerSSH print:
`{"timestamp":"2021-02-23T01:18:50+01:00","level":"warning","module":"ssh","details":"authentication backend currently unavailable (failed on HTTP request)"}
{"timestamp":"2021-02-23T01:18:50+01:00","level":"warning","module":"ssh","details":"authentication backend currently unavailable (keyboard-interactive authentication not  available)"}`

My auth server print:
`2021/02/23 01:18:50 http: TLS handshake error from [::1]:35972: remote error: tls: bad certificate`

Curl work correct from authServer dir:
`curl --key example/clientCert1/client.key --cert example/clientCert1/client.crt --cacert example/server/server_cert.pem -L https://localhost:8081/password -d '{"username":"user1","passwordBase64":"dGVzdA==", "remoteAddress": "10.5.4.12"}'`

...

## Have you read the readme in its entirety?
Yes
...

## What have you tried to resolve this problem?
- Set log in ContainerSSH to debug
- Use Main Branch
- Remove client cert form ContainerSSH config
- Change file reference to cert content
- Clone ContainerSSH/http and add debug Infromations
...

auth server use the '-config' flag and in the authServer/example folder is the used config

**Comment by janoszen** [comment]
Hey @patsys,

Thank you for your request. Please keep in mind that the 0.4.0-PR3 release is not final yet.

Could you please provide the steps you used to generate the TLS certificates so we can replicate the issue? What kind of certificates are you using for your CA and client certificates? What server are you using?

If you need to regenerate your certificates please take a look at the [reference manual for the upcoming 0.4 release](https://containerssh.io/reference/upcoming/auth/#client-authentication).

Thank you for your help.

**Comment by janoszen** [comment]
Nevermind, I see your code in your repo, let me check what went wrong.

**Comment by janoszen** [comment]
@patsys it seems we have a bug and we don't adequately log the problem with the client requests. This will be fixed with the final 0.4 release.

The root cause is the following:

> Post "https://localhost:8443/password": x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0

In other words, you need to add SANs to your certificates in order for this to work. Please follow [this guide](https://containerssh.io/reference/upcoming/auth/#client-authentication) to generate your certificates and let us know if it works.

**Comment by patsys** [comment]
Hello @janoszen,

Thank you for the quick answer it was the missing SAN.
Curl use also the Common Name to validate and go only subjectAltName.

**Comment by janoszen** [comment]
@patsys does it work for you now?

**Comment by patsys** [comment]
yes this part works, very thanks!

**Comment by janoszen** [comment]
Thanks for confirming. Please let us know if you run into any more issues. We are preparing to release the final 0.4 version and your feedback is most helpful.
