### ISSUE TITLE
SSH Key not supported by Auth

### ISSUE THREAD

**Issue by patsys** [ContainerSSH/ContainerSSH#111]
## Please describe what you need help with
By Key auth I get an Error from Contianerssh, password login work correct:
`{"timestamp":"2021-02-25T03:58:30+01:00","level":"warning","module":"ssh","details":"authentication backend currently unavailable (the backend handler does not support authentication)"}
{"timestamp":"2021-02-25T03:58:30+01:00","level":"warning","module":"ssh","details":"authentication backend currently unavailable (keyboard-interactive authentication not available)"}`

I use Version 0.4.0-RC3 mit auth v0.9.3 Library

ContainerSSH is Config can found in https://github.com/patsys/containerSSH/blob/develop/example/config.yml
...

## Have you read the readme in its entirety?
Yes

...

## What have you tried to resolve this problem?
- ContainerSSH log to debug level
- Check auth server work correct
  - Curl request return `{"success":true}`
  - Add Debug output
...

**Comment by janoszen** [comment]
Thank you for reporting this @patsys, this bug has already been identified and will be fixed in the next preview release.

**Comment by janoszen** [comment]
@patsys ContainerSSH 0.4.0-PR4 is now released, this should be resolved now. Could you please test?

**Comment by patsys** [comment]
@janoszen it work correct, Thanks.

**Comment by janoszen** [comment]
Thank you, I'll close the issue,
