### ISSUE TITLE
Switching code license to MIT-0

### ISSUE THREAD

**Issue by janoszen** [ContainerSSH/ContainerSSH#139]
Hello everyone,

I'm proposing to switch to the MIT-0 license. This would remove the requirement to distribute the license with the source code or attribute us as the source of the code.

This would make it easier for others to take parts of the ContainerSSH code and reuse it in other projects.

What this would not affect:

- The built ContainerSSH binaries (they contain source code from various projects, so licenses are still required)
- The documentation (up for separate discussion)
- The ContainerSSH name, logos and assets (subject to the brand license in the [branding repo](https://github.com/containerssh/branding)

Are all the following contributors OK with the move? If yes please comment +1 below.

- @ecrazor1911 
- @mhmxs 
- @sanjabonic

**Comment by ecrazor1911** [comment]
+1

**Comment by janoszen** [comment]
Thank you everyone, we are switching the code license. We'll talk about docs and assets in a separate issue.
