### ISSUE TITLE
Health check endpoint

### ISSUE THREAD

**Issue by ghost** [ContainerSSH/ContainerSSH#164]
## Please describe what you would like to see in ContainerSSH

ContainerSSH should offer a dedicated HTTP health check endpoint that lets load balancers check if CotnainerSSH is up.

## Please describe the solution you'd like

ContainerSSH should offer a separate HTTP endpoint that returns OK when all services are up and removes the OK status before the shutdown begins. ContainerSSH should also offer a binary within the container image that lets one check if ContainerSSH is up or down.

## Please describe your use case

Containerized deployments need this to offer load balancing.

**Comment by tsipinakis** [comment]
[Implemented in 0.5](https://containerssh.io/v0.5/reference/health/)
