### ISSUE TITLE
ARM / 32 bit support

### ISSUE THREAD

**Issue by ghost** [ContainerSSH/ContainerSSH#165]
## Please describe what you would like to see in ContainerSSH

Add builds for ARM64 and ARM32

## Please describe the solution you'd like

We need ARM64 (ARM 8) and ARM32 (ARM 7) binary builds.

## Please describe your use case

ContainerSSH should work in embedded systems.

**Comment by aniston** [comment]
How about docker images for ARM64, Hetzner a VPS provider has cheap ARM VPS plans and I use one for less than €10/month. I would not doubt that many already are on ARM64 VPS plans.

But probably I jumped into the wrong issue and should start a new one for "Docker arm64 image".
