### ISSUE TITLE
ContainerSSH config server library ignores inline JSON option

### ISSUE THREAD

**Issue by ne-bknn** [ContainerSSH/ContainerSSH#201]
## Please describe what you need help with:
I have a custom configuration server based on [containerssh-testauthconfigserver](https://github.com/ContainerSSH/ContainerSSH/blob/main/cmd/containerssh-testauthconfigserver/main.go). It just fetches an image name from redis by username. Unfortunately, ContainerSSH seems to ignore this custom config, since it always drops me in `containerssh/containerssh-guest-image`. Configuration server replies with this JSON: https://pastebin.com/Pt2LHqWW.

My system-wide configuration: https://github.com/ne-bknn/CSSH/blob/master/config/config.yml.

Also, `containerssh-testauthconfigserver` seems to be broken, since `config.Docker.Execution.Launch.ContainerConfig` is `nil` and I had to manually set it to `Config` structure from `docker/docker` to make it work. Is it correct or I've done something stupid?

Maybe I'm not setting some important field in my configuration? Are null-valued fields in server's response overwrite system-wide configuration?

[My config handler](https://github.com/ne-bknn/CSSH/blob/5b8997855088b0550548f1b423aa037982412b80/authconfig/main.go#L92) (this code is far from being well-written or production-ready, sorry).

## Have you read the [troubleshooting guide](https://containerssh.io/reference/troubleshooting/)?
Yep, tried everything except strace'ing it (seems to be useless in my problem). 

## What have you tried to resolve this problem?
I do not see any way to resolve this problem by myself other than blindly trying to modify configuration options.

**Comment by janoszen** [comment]
Hello @ne-bknn thank you for reporting this issue. Please give us a bit of time to figure out what the problem with your setup is.

**Comment by janoszen** [comment]
@ne-bknn we tracked down the issue to a bug in the [configuration library](https://github.com/containerssh/configuration). The JSON encoding process ignores the `",inline"` tag, which causes the JSON structure to be incorrect and contain the `Launch` part that should be omitted.

We will fix the bug and release a new configuration library in roughly a week to address this issue and ping you here. You should then update the Go module dependencies in order to use the new library.

**Comment by janoszen** [comment]
Hello @ne-bknn, the fix has been merged and will be released shortly with ContainerSSH version 0.4.1.

**Comment by janoszen** [comment]
@ne-bknn ContainerSSH preview version `0.4.1-alpha.2` is now released, if you can please try it out, it should fix your issue. We will release the final `0.4.1` roughly tomorrow.

**Comment by janoszen** [comment]
@ne-bknn the new version has been released.

**Comment by ne-bknn** [comment]
Everything works perfectly, thanks!
