### ISSUE TITLE
Quickstart example not working (using Docker Desktop for Mac)

### ISSUE THREAD

**Issue by BartKoppers** [ContainerSSH/ContainerSSH#53]
## Quickstart example not working (using Docker Desktop for Mac)

Cannot get the Quickstart example working on my Macbook Pro

## To Reproduce

1. Installed Docker Desktop Mac, open Terminal
2. mkdir ~/Testing ; git clone https://github.com/ContainerSSH/containerssh.git
3. cd ~/Testing/containerssh/example

`docker-compose build`

> containerssh uses an image, skipping
authconfig uses an image, skipping

`docker-compose up`

> Recreating example_containerssh_1 ... done
Starting example_authconfig_1     ... done
Attaching to example_authconfig_1, example_containerssh_1
authconfig_1    | standard_init_linux.go:211: exec user process caused "no such file or directory"
example_authconfig_1 exited with code 1
containerssh_1  | {"timestamp":"2020-10-23T11:15:29Z","level":"warning","message":"failed to load GeoIP2 database, falling back to dummy provider (open /var/lib/GeoIP/GeoIP2-Country.mmdb: no such file or directory)"}
containerssh_1  | {"timestamp":"2020-10-23T11:15:29Z","level":"info","message":"starting SSH server on 0.0.0.0:2222"}

In a new Terminal: ` ssh foo@127.0.0.1 -p 2222`

> foo@127.0.0.1's password: 
Permission denied, please try again.
foo@127.0.0.1's password: 
Permission denied, please try again.
foo@127.0.0.1's password: 
foo@127.0.0.1: Permission denied (password).

Cannot login, with/without a password. 
Same using `ssh busybox@127.0.0.1 -p 2222`

## Expected behavior

Some login possible...

## Version

git branch
> * stable

docker -v
>Docker version 19.03.13, build 4484c46d9d

docker-compose -v
>docker-compose version 1.27.4, build 40524192

**Comment by janoszen** [comment]
Hello @BartKoppers, thank you for reporting this issue, I'll take a look soon and push a fix for the examples.

**Comment by janoszen** [comment]
Hello @BartKoppers thank you for your patience. The example folder should now contain an up-to-date example. I do not have a Mac available, but I'm fairly confident it should work now. If it doesn't please let me know and I'll do my best to find some help to debug it.
