### ISSUE TITLE
outdated replace usage in go.mod

### ISSUE THREAD

**Issue by Morty-luo** [ContainerSSH/ContainerSSH#545]
There are replace lines in go.mod pinning `golang.org/x/text` to `v0.3.3`. However, according to [GO-2022-1059](https://pkg.go.dev/vuln/GO-2022-1059), version of `golang.org/x/text` before `v0.3.8` suffers potential vulnerability. Should them be updated? <br>
<https://github.com/ContainerSSH/ContainerSSH/blob/main/go.mod>(Line 118 to 122)
```txt
replace (
	golang.org/x/text v0.3.0 => golang.org/x/text v0.3.3
	golang.org/x/text v0.3.1 => golang.org/x/text v0.3.3
	golang.org/x/text v0.3.2 => golang.org/x/text v0.3.3
)
```

**Comment by inFocus7** [comment]
With the above work merged, is this issue complete/close-able?

**Comment by tsipinakis** [comment]
Indeed, thanks!
