### ISSUE TITLE
SSH port forwarding

### ISSUE THREAD

**Issue by ghost** [ContainerSSH/ContainerSSH#58]
Implement SSH port forwarding using an in-container agent. Depends on #57

**Comment by janoszen** [comment]
Potential agent: https://github.com/norouter/norouter

**Comment by janoszen** [comment]
RFC section: https://tools.ietf.org/html/rfc4254#section-7

**Comment by tsipinakis** [comment]
Doing some cleanup, closing this as it has been implemented already for 0.5.
