### ISSUE TITLE
Maximum time of guest execution

### ISSUE THREAD

**Issue by pklanka** [ContainerSSH/ContainerSSH#596]
## Please describe what you would like to see in ContainerSSH

Could we have a feature in config that illustrates maximum time a given session can be alive. This would be quite useful in honeypot scenarios.

## Please describe your use case

We want to limit the amount of time each session would persist as a containerssh connection especially within honeypot scenarios. This timeout will forcibly kill the ssh connection once backend hits the timeout.

**Comment by tsipinakis** [comment]
Hi @pklanka thanks for the feature request. I'll close this as a duplicate of #593  :) . However it is a good idea and doesn't sound too complex to implement. If someone wants to take a shot at implementing it let me know.
