### ISSUE TITLE
Please Deploy ContainerSSH with latest libcontainerssh Module

### ISSUE THREAD

**Issue by seanocca** [ContainerSSH/ContainerSSH#603]
## Please describe what you need help with:

We are missing the `scope` argument for OIDC Azure AD v2.0 auth.
This has been updated in the latest libcontainerssh module but has not been released and containerised for public consumption yet
...

## Have you read the [troubleshooting guide](https://containerssh.io/reference/troubleshooting/)?

Yes I have and it did not help in this situation

## What have you tried to resolve this problem?

Manipulated multiple settings that you have made available but none have worked.
I have a temporary work around that is not favourable.
I have cloned this repository locally and run go mod vendor to pull the module code into my repository. Then I am building a custom container.

**Comment by tsipinakis** [comment]
You're right, I have delayed releasing this for quite a while. I pushed the libcontainerssh tag, once tests pass I'll tag and push a new point release.
